### ISSUE TITLE
Bug /addindex and /removeindex

### ISSUE THREAD

**Issue by TechBotGit** [TechBotGit/bot#21]
Workflow:
addindex —> bot shutdown —>  **removeindex (error)** --> **addindex (error)**

By: Hans

**Comment by TechBotGit** [comment]
@hanstananda aku ndak nemu error ini se Hans, coba km re run lagi, error e kenapa to be exact?

**Comment by hanstananda** [comment]
Callback Query: 1897004777796328809 441680843 CZ1003
CZ1003
CZ1005
{'CZ1003': {'index': '10107', 'event_id': ['iudfn0spohekr7nh5c88sad5rg', 'fnvtjh96n0rqgg5jdfrdcup3gs', 'hhl62gm6eoorfnb2fdpo6en9pk',
'feji13v7anb5423l7hpnb96rn8']}}
str:
{"CZ1003": {"index": "10107", "event_id": ["iudfn0spohekr7nh5c88sad5rg", "fnvtjh96n0rqgg5jdfrdcup3gs", "hhl62gm6eoorfnb2fdpo6en9pk",
"feji13v7anb5423l7hpnb96rn8"]}}
Traceback (most recent call last):
  File "../resources/modules\BotClass.py", line 579, in RemoveIndexCommand
    for evt_id in course_code_db_obj[course_code]['event_id']:
KeyError: 'CZ1005'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hans-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\telepot\loop.py", line 37, in run_forever
    self._handle(msg)
  File "C:\Users\Hans-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\telepot\helper.py", line 1031, in route
    return fn(msg, *args, **kwargs)
  File "../resources/modules\BotClass.py", line 369, in on_callback_query
    BotCommandObject.RemoveIndexCommand(chat_id)
  File "../resources/modules\BotClass.py", line 583, in RemoveIndexCommand
    raise ValueError
ValueError

**Comment by hanstananda** [comment]
#RIP

**Comment by hanstananda** [comment]
![image](https://user-images.githubusercontent.com/21126223/31088869-b11831cc-a7d4-11e7-856d-284018e4bc98.png)
#solved
